# Generated by Django 6.0.5 on 2026-07-29 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
